//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touhou_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touhou_Launcher.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string allFilter {
            get {
                return ResourceManager.GetString("allFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antinomy of Common Flowers.
        /// </summary>
        public static string AoCF {
            get {
                return ResourceManager.GetString("AoCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoCF.
        /// </summary>
        public static string AoCFShort {
            get {
                return ResourceManager.GetString("AoCFShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 15.5: Antinomy of Common Flowers.
        /// </summary>
        public static string AoCFTitle {
            get {
                return ResourceManager.GetString("AoCFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ascendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("ascendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Close.
        /// </summary>
        public static string autoClose {
            get {
                return ResourceManager.GetString("autoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically close the launcher after launching a game.
        /// </summary>
        public static string autoCloseToolTip {
            get {
                return ResourceManager.GetString("autoCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey Banner.
        /// </summary>
        public static string bannerOffLabel {
            get {
                return ResourceManager.GetString("bannerOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the grey banner.
        /// </summary>
        public static string bannerOffSelectTitle {
            get {
                return ResourceManager.GetString("bannerOffSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored Banner.
        /// </summary>
        public static string bannerOnLabel {
            get {
                return ResourceManager.GetString("bannerOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the colored banner.
        /// </summary>
        public static string bannerOnSelectTitle {
            get {
                return ResourceManager.GetString("bannerOnSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Settings.
        /// </summary>
        public static string bannerSettings {
            get {
                return ResourceManager.GetString("bannerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom banner.
        /// </summary>
        public static string chkCustomBanner {
            get {
                return ResourceManager.GetString("chkCustomBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Game.
        /// </summary>
        public static string configureToolStripMenuItem {
            get {
                return ResourceManager.GetString("configureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap Profile:.
        /// </summary>
        public static string crapLabel {
            get {
                return ResourceManager.GetString("crapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string customAdd {
            get {
                return ResourceManager.GetString("customAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category &apos;{0}&apos; and all of its contents?.
        /// </summary>
        public static string customCategoryDeleteConfirm {
            get {
                return ResourceManager.GetString("customCategoryDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        public static string customDeleteConfirm {
            get {
                return ResourceManager.GetString("customDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Games.
        /// </summary>
        public static string customGames {
            get {
                return ResourceManager.GetString("customGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.exe:.
        /// </summary>
        public static string customLabel {
            get {
                return ResourceManager.GetString("customLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Drealing Character.
        /// </summary>
        public static string DDC {
            get {
                return ResourceManager.GetString("DDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDC.
        /// </summary>
        public static string DDCShort {
            get {
                return ResourceManager.GetString("DDCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14: Double Dealing Character.
        /// </summary>
        public static string DDCTitle {
            get {
                return ResourceManager.GetString("DDCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese/vpatch.ini, English (non-THCRAP), Custom.exe, thcrap.
        /// </summary>
        public static string defaultExec {
            get {
                return ResourceManager.GetString("defaultExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Executable:.
        /// </summary>
        public static string defaultLabel {
            get {
                return ResourceManager.GetString("defaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string deleteCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string descendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("descendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detailsToolStripMenuItem {
            get {
                return ResourceManager.GetString("detailsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Spoiler.
        /// </summary>
        public static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        public static string DSShort {
            get {
                return ResourceManager.GetString("DSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.3: Double Spoiler.
        /// </summary>
        public static string DSTitle {
            get {
                return ResourceManager.GetString("DSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Executable:.
        /// </summary>
        public static string enLabel {
            get {
                return ResourceManager.GetString("enLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embodiment of Scarlet Devil.
        /// </summary>
        public static string EoSD {
            get {
                return ResourceManager.GetString("EoSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EoSD.
        /// </summary>
        public static string EoSDShort {
            get {
                return ResourceManager.GetString("EoSDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 06: the Embodiment of Scarlet Devil.
        /// </summary>
        public static string EoSDTitle {
            get {
                return ResourceManager.GetString("EoSDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Appdata Folder.
        /// </summary>
        public static string errorAppdataNotFound {
            get {
                return ResourceManager.GetString("errorAppdataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set thcrap&apos;s location.
        /// </summary>
        public static string errorcrapNotFound {
            get {
                return ResourceManager.GetString("errorcrapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found.
        /// </summary>
        public static string errorFileNotFound {
            get {
                return ResourceManager.GetString("errorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game.
        /// </summary>
        public static string errorGameNotFound {
            get {
                return ResourceManager.GetString("errorGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project II&apos;s configuration ini is not valid..
        /// </summary>
        public static string errorInvalidNP2INI {
            get {
                return ResourceManager.GetString("errorInvalidNP2INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Neko Project 2&apos;s location.
        /// </summary>
        public static string errorNP2NotFound {
            get {
                return ResourceManager.GetString("errorNP2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file as image:
        ///.
        /// </summary>
        public static string errorOpenImage {
            get {
                return ResourceManager.GetString("errorOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Games Selected.
        /// </summary>
        public static string errorRandomListEmpty {
            get {
                return ResourceManager.GetString("errorRandomListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Replays folder.
        /// </summary>
        public static string errorReplaysNotFound {
            get {
                return ResourceManager.GetString("errorReplaysNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find vpatch.ini.
        /// </summary>
        public static string errorvpatchNotFound {
            get {
                return ResourceManager.GetString("errorvpatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files.
        /// </summary>
        public static string executableFilter {
            get {
                return ResourceManager.GetString("executableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting Games.
        /// </summary>
        public static string fightingGroup {
            get {
                return ResourceManager.GetString("fightingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Configuration: .
        /// </summary>
        public static string gameConfiguration {
            get {
                return ResourceManager.GetString("gameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Executable.
        /// </summary>
        public static string gameSelectTitle {
            get {
                return ResourceManager.GetString("gameSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Fairy Wars.
        /// </summary>
        public static string GFW {
            get {
                return ResourceManager.GetString("GFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFW.
        /// </summary>
        public static string GFWShort {
            get {
                return ResourceManager.GetString("GFWShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.8: Great Fairy Wars.
        /// </summary>
        public static string GFWTitle {
            get {
                return ResourceManager.GetString("GFWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image Files.
        /// </summary>
        public static string hdiFilter {
            get {
                return ResourceManager.GetString("hdiFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game HDI:.
        /// </summary>
        public static string hdiLabel {
            get {
                return ResourceManager.GetString("hdiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game&apos;s HDI.
        /// </summary>
        public static string hdiSelectTitle {
            get {
                return ResourceManager.GetString("hdiSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopeless Masquerade.
        /// </summary>
        public static string HM {
            get {
                return ResourceManager.GetString("HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM.
        /// </summary>
        public static string HMShort {
            get {
                return ResourceManager.GetString("HMShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 13.5: Hopeless Masquerade.
        /// </summary>
        public static string HMTitle {
            get {
                return ResourceManager.GetString("HMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highly Responsive to Prayers.
        /// </summary>
        public static string HRtP {
            get {
                return ResourceManager.GetString("HRtP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRtP.
        /// </summary>
        public static string HRtPShort {
            get {
                return ResourceManager.GetString("HRtPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 01: Highly Responsive to Prayers.
        /// </summary>
        public static string HRtPTitle {
            get {
                return ResourceManager.GetString("HRtPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Star in Four Seasons.
        /// </summary>
        public static string HSiFS {
            get {
                return ResourceManager.GetString("HSiFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSiFS.
        /// </summary>
        public static string HSiFSShort {
            get {
                return ResourceManager.GetString("HSiFSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 16: Hidden Star in Four Seasons.
        /// </summary>
        public static string HSiFSTitle {
            get {
                return ResourceManager.GetString("HSiFSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immaterial and Missing Power.
        /// </summary>
        public static string IaMP {
            get {
                return ResourceManager.GetString("IaMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IaMP.
        /// </summary>
        public static string IaMPShort {
            get {
                return ResourceManager.GetString("IaMPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 7.5: Immaterial and Missing Power.
        /// </summary>
        public static string IaMPTitle {
            get {
                return ResourceManager.GetString("IaMPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string imageFilter {
            get {
                return ResourceManager.GetString("imageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperishable Night.
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string INShort {
            get {
                return ResourceManager.GetString("INShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 08: Imperishable Night.
        /// </summary>
        public static string INTitle {
            get {
                return ResourceManager.GetString("INTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible Spell Card.
        /// </summary>
        public static string ISC {
            get {
                return ResourceManager.GetString("ISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISC.
        /// </summary>
        public static string ISCShort {
            get {
                return ResourceManager.GetString("ISCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14.3: Impossible Spell Card.
        /// </summary>
        public static string ISCTitle {
            get {
                return ResourceManager.GetString("ISCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese/vpatch Executable:.
        /// </summary>
        public static string jpLabel {
            get {
                return ResourceManager.GetString("jpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string langLabel {
            get {
                return ResourceManager.GetString("langLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icons.
        /// </summary>
        public static string largeIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("largeIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Settings.
        /// </summary>
        public static string launcherSettings {
            get {
                return ResourceManager.GetString("launcherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string listToolStripMenuItem {
            get {
                return ResourceManager.GetString("listToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus Land Story.
        /// </summary>
        public static string LLS {
            get {
                return ResourceManager.GetString("LLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLS.
        /// </summary>
        public static string LLSShort {
            get {
                return ResourceManager.GetString("LLSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 04: Lotus Land Story.
        /// </summary>
        public static string LLSTitle {
            get {
                return ResourceManager.GetString("LLSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy of Lunatic Kingdom.
        /// </summary>
        public static string LoLK {
            get {
                return ResourceManager.GetString("LoLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoLK.
        /// </summary>
        public static string LoLKShort {
            get {
                return ResourceManager.GetString("LoLKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 15: Legacy of Lunatic Kingdom.
        /// </summary>
        public static string LoLKTitle {
            get {
                return ResourceManager.GetString("LoLKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Games.
        /// </summary>
        public static string mainGroup {
            get {
                return ResourceManager.GetString("mainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain of Faith.
        /// </summary>
        public static string MoF {
            get {
                return ResourceManager.GetString("MoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoF.
        /// </summary>
        public static string MoFShort {
            get {
                return ResourceManager.GetString("MoFShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 10: Mountain of Faith.
        /// </summary>
        public static string MoFTitle {
            get {
                return ResourceManager.GetString("MoFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystic Square.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string MSShort {
            get {
                return ResourceManager.GetString("MSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 05: Mystic Square.
        /// </summary>
        public static string MSTitle {
            get {
                return ResourceManager.GetString("MSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string newCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("newCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project II Location.
        /// </summary>
        public static string np2Label {
            get {
                return ResourceManager.GetString("np2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neko Project II&apos;s executable.
        /// </summary>
        public static string np2SelectTitle {
            get {
                return ResourceManager.GetString("np2SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appdata Folder.
        /// </summary>
        public static string openAppdata {
            get {
                return ResourceManager.GetString("openAppdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string openFolderToolStripMenuItem {
            get {
                return ResourceManager.GetString("openFolderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Neko Project II Folder.
        /// </summary>
        public static string openNP2Folder {
            get {
                return ResourceManager.GetString("openNP2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Replays Folder.
        /// </summary>
        public static string openReplays {
            get {
                return ResourceManager.GetString("openReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vpatch.ini.
        /// </summary>
        public static string openvpatch {
            get {
                return ResourceManager.GetString("openvpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Applocale.
        /// </summary>
        public static string openWithApplocaleToolStripMenuItem {
            get {
                return ResourceManager.GetString("openWithApplocaleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Games.
        /// </summary>
        public static string otherGroup {
            get {
                return ResourceManager.GetString("otherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-98 Game Settings.
        /// </summary>
        public static string pc98Settings {
            get {
                return ResourceManager.GetString("pc98Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Cherry Blossom.
        /// </summary>
        public static string PCB {
            get {
                return ResourceManager.GetString("PCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB.
        /// </summary>
        public static string PCBShort {
            get {
                return ResourceManager.GetString("PCBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 07: Perfect Cherry Blossom.
        /// </summary>
        public static string PCBTitle {
            get {
                return ResourceManager.GetString("PCBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Random.
        /// </summary>
        public static string playRandomToolStripMenuItem {
            get {
                return ResourceManager.GetString("playRandomToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasmagoria of Dim. Dream.
        /// </summary>
        public static string PoDD {
            get {
                return ResourceManager.GetString("PoDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoDD.
        /// </summary>
        public static string PoDDShort {
            get {
                return ResourceManager.GetString("PoDDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 03: Phantasmagoria of Dim. Dream.
        /// </summary>
        public static string PoDDTitle {
            get {
                return ResourceManager.GetString("PoDDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasmagoria of Flower View.
        /// </summary>
        public static string PoFV {
            get {
                return ResourceManager.GetString("PoFV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoFV.
        /// </summary>
        public static string PoFVShort {
            get {
                return ResourceManager.GetString("PoFVShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 09: Phantasmagoria of Flower View.
        /// </summary>
        public static string PoFVTitle {
            get {
                return ResourceManager.GetString("PoFVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string randomAll {
            get {
                return ResourceManager.GetString("randomAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games that will be included in the
        ///random game option:.
        /// </summary>
        public static string randomLabel {
            get {
                return ResourceManager.GetString("randomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string randomNone {
            get {
                return ResourceManager.GetString("randomNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Game Settings.
        /// </summary>
        public static string randomSettings {
            get {
                return ResourceManager.GetString("randomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a Random Game.
        /// </summary>
        public static string RandomTitle {
            get {
                return ResourceManager.GetString("RandomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Category.
        /// </summary>
        public static string renameCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string renameToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &apos;{0}&apos; to:
        ///&apos;{1}&apos;.
        /// </summary>
        public static string replayDownload {
            get {
                return ResourceManager.GetString("replayDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Replay?.
        /// </summary>
        public static string replayDownloadTitle {
            get {
                return ResourceManager.GetString("replayDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Files.
        /// </summary>
        public static string replayFilter {
            get {
                return ResourceManager.GetString("replayFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player replays full and Touhou 10 does not support user replays.
        ///.
        /// </summary>
        public static string replayFull {
            get {
                return ResourceManager.GetString("replayFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replays.
        /// </summary>
        public static string replays {
            get {
                return ResourceManager.GetString("replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subterranean Animism.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string SAShort {
            get {
                return ResourceManager.GetString("SAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 11: Subterranean Animism.
        /// </summary>
        public static string SATitle {
            get {
                return ResourceManager.GetString("SATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show tray icon.
        /// </summary>
        public static string showTray {
            get {
                return ResourceManager.GetString("showTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icons.
        /// </summary>
        public static string smallIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("smallIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story of Eastern Wonderland.
        /// </summary>
        public static string SoEW {
            get {
                return ResourceManager.GetString("SoEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoEW.
        /// </summary>
        public static string SoEWShort {
            get {
                return ResourceManager.GetString("SoEWShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 02: the Story of Eastern Wonderland.
        /// </summary>
        public static string SoEWTitle {
            get {
                return ResourceManager.GetString("SoEWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string sortToolStripMenuItem {
            get {
                return ResourceManager.GetString("sortToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot the Bullet.
        /// </summary>
        public static string StB {
            get {
                return ResourceManager.GetString("StB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StB.
        /// </summary>
        public static string StBShort {
            get {
                return ResourceManager.GetString("StBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 9.5: Shoot the Bullet.
        /// </summary>
        public static string StBTitle {
            get {
                return ResourceManager.GetString("StBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarlet Weather Rhapsody.
        /// </summary>
        public static string SWR {
            get {
                return ResourceManager.GetString("SWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWR.
        /// </summary>
        public static string SWRShort {
            get {
                return ResourceManager.GetString("SWRShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 10.5: Scarlet Weather Rhapsody.
        /// </summary>
        public static string SWRTitle {
            get {
                return ResourceManager.GetString("SWRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten Desires.
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        public static string TDShort {
            get {
                return ResourceManager.GetString("TDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 13: Ten Desires.
        /// </summary>
        public static string TDTitle {
            get {
                return ResourceManager.GetString("TDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string tileToolStripMenuItem {
            get {
                return ResourceManager.GetString("tileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou Launcher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Fantastic Object.
        /// </summary>
        public static string UFO {
            get {
                return ResourceManager.GetString("UFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFO.
        /// </summary>
        public static string UFOShort {
            get {
                return ResourceManager.GetString("UFOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12: Undefined Fantastic Object.
        /// </summary>
        public static string UFOTitle {
            get {
                return ResourceManager.GetString("UFOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban Legend in Limbo.
        /// </summary>
        public static string ULiL {
            get {
                return ResourceManager.GetString("ULiL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULiL.
        /// </summary>
        public static string ULiLShort {
            get {
                return ResourceManager.GetString("ULiLShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14.5: Urban Legend in Limbo.
        /// </summary>
        public static string ULiLTitle {
            get {
                return ResourceManager.GetString("ULiLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisoutensoku.
        /// </summary>
        public static string UoNL {
            get {
                return ResourceManager.GetString("UoNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisoutensoku.
        /// </summary>
        public static string UoNLShort {
            get {
                return ResourceManager.GetString("UoNLShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.5: Hisoutensoku.
        /// </summary>
        public static string UoNLTitle {
            get {
                return ResourceManager.GetString("UoNLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Applocale.
        /// </summary>
        public static string useApplocale {
            get {
                return ResourceManager.GetString("useApplocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet Detector.
        /// </summary>
        public static string VD {
            get {
                return ResourceManager.GetString("VD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VD.
        /// </summary>
        public static string VDShort {
            get {
                return ResourceManager.GetString("VDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 16.5: Violet Detector.
        /// </summary>
        public static string VDTitle {
            get {
                return ResourceManager.GetString("VDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Game Settings.
        /// </summary>
        public static string windowsSettings {
            get {
                return ResourceManager.GetString("windowsSettings", resourceCulture);
            }
        }
    }
}
