//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touhou_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_jp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touhou_Launcher.Resources_jp", typeof(Resources_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべてのファイル.
        /// </summary>
        public static string allFilter {
            get {
                return ResourceManager.GetString("allFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方憑依華.
        /// </summary>
        public static string AoCF {
            get {
                return ResourceManager.GetString("AoCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 憑依華.
        /// </summary>
        public static string AoCFShort {
            get {
                return ResourceManager.GetString("AoCFShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方憑依華　～ Antinomy of Common Flowers.
        /// </summary>
        public static string AoCFTitle {
            get {
                return ResourceManager.GetString("AoCFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昇順.
        /// </summary>
        public static string ascendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("ascendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動終了.
        /// </summary>
        public static string autoClose {
            get {
                return ResourceManager.GetString("autoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームを起動した後、自動的にランチャーを閉じます.
        /// </summary>
        public static string autoCloseToolTip {
            get {
                return ResourceManager.GetString("autoCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナー（白黒）.
        /// </summary>
        public static string bannerOffLabel {
            get {
                return ResourceManager.GetString("bannerOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナー（白黒）を指定する.
        /// </summary>
        public static string bannerOffSelectTitle {
            get {
                return ResourceManager.GetString("bannerOffSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナー.
        /// </summary>
        public static string bannerOnLabel {
            get {
                return ResourceManager.GetString("bannerOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナーを指定する.
        /// </summary>
        public static string bannerOnSelectTitle {
            get {
                return ResourceManager.GetString("bannerOnSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナーの設定.
        /// </summary>
        public static string bannerSettings {
            get {
                return ResourceManager.GetString("bannerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 120 x 44.
        /// </summary>
        public static string bannerSize {
            get {
                return ResourceManager.GetString("bannerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バナーの表示.
        /// </summary>
        public static string bannerToolStripMenuItem {
            get {
                return ResourceManager.GetString("bannerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参照.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色を指定.
        /// </summary>
        public static string btnCustomText {
            get {
                return ResourceManager.GetString("btnCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        public static string buttonToolStripMenuItem {
            get {
                return ResourceManager.GetString("buttonToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタムバナーを使用.
        /// </summary>
        public static string chkCustomBanner {
            get {
                return ResourceManager.GetString("chkCustomBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定した色を使用.
        /// </summary>
        public static string chkCustomText {
            get {
                return ResourceManager.GetString("chkCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string configureToolStripMenuItem {
            get {
                return ResourceManager.GetString("configureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrapの設定.
        /// </summary>
        public static string crapConfigure {
            get {
                return ResourceManager.GetString("crapConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap_loaderの場所：.
        /// </summary>
        public static string crapDirLabel {
            get {
                return ResourceManager.GetString("crapDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrapプロファイル:.
        /// </summary>
        public static string crapLabel {
            get {
                return ResourceManager.GetString("crapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デフォルト.
        /// </summary>
        public static string crapResetStartingRepo {
            get {
                return ResourceManager.GetString("crapResetStartingRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap起動用リポジトリ:.
        /// </summary>
        public static string crapStartingRepoLabel {
            get {
                return ResourceManager.GetString("crapStartingRepoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームを追加.
        /// </summary>
        public static string customAdd {
            get {
                return ResourceManager.GetString("customAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」とその中にいるすべてを削除しますか？.
        /// </summary>
        public static string customCategoryDeleteConfirm {
            get {
                return ResourceManager.GetString("customCategoryDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」を削除しますか？.
        /// </summary>
        public static string customDeleteConfirm {
            get {
                return ResourceManager.GetString("customDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同人ゲーム.
        /// </summary>
        public static string customGames {
            get {
                return ResourceManager.GetString("customGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.exe:.
        /// </summary>
        public static string customLabel {
            get {
                return ResourceManager.GetString("customLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームを削除する.
        /// </summary>
        public static string customRemove {
            get {
                return ResourceManager.GetString("customRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方輝針城.
        /// </summary>
        public static string DDC {
            get {
                return ResourceManager.GetString("DDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輝針城.
        /// </summary>
        public static string DDCShort {
            get {
                return ResourceManager.GetString("DDCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方輝針城　～ Double Dealing Character.
        /// </summary>
        public static string DDCTitle {
            get {
                return ResourceManager.GetString("DDCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語/vpatch.ini, 英語 (non-THCRAP), Custom.exe, thcrap.
        /// </summary>
        public static string defaultExec {
            get {
                return ResourceManager.GetString("defaultExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デフォルトで開く:.
        /// </summary>
        public static string defaultLabel {
            get {
                return ResourceManager.GetString("defaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string deleteCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降順.
        /// </summary>
        public static string descendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("descendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 説明.
        /// </summary>
        public static string descriptionColumn {
            get {
                return ResourceManager.GetString("descriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細.
        /// </summary>
        public static string detailsToolStripMenuItem {
            get {
                return ResourceManager.GetString("detailsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルスポイラー.
        /// </summary>
        public static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルスポイラー.
        /// </summary>
        public static string DSShort {
            get {
                return ResourceManager.GetString("DSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルスポイラー　～ 東方文花帖.
        /// </summary>
        public static string DSTitle {
            get {
                return ResourceManager.GetString("DSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Executable:.
        /// </summary>
        public static string enLabel {
            get {
                return ResourceManager.GetString("enLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方紅魔郷.
        /// </summary>
        public static string EoSD {
            get {
                return ResourceManager.GetString("EoSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紅魔郷.
        /// </summary>
        public static string EoSDShort {
            get {
                return ResourceManager.GetString("EoSDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方紅魔郷　～ the Embodiment of Scarlet Devil.
        /// </summary>
        public static string EoSDTitle {
            get {
                return ResourceManager.GetString("EoSDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appdataフォルダが見つりません.
        /// </summary>
        public static string errorAppdataNotFound {
            get {
                return ResourceManager.GetString("errorAppdataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrapのプロファイルを設定してください.
        /// </summary>
        public static string errorcrapConfigNotSet {
            get {
                return ResourceManager.GetString("errorcrapConfigNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrapのパスを指定してください.
        /// </summary>
        public static string errorcrapNotFound {
            get {
                return ResourceManager.GetString("errorcrapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが見つかりません.
        /// </summary>
        public static string errorFileNotFound {
            get {
                return ResourceManager.GetString("errorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームファイルが見つからない。右クリックメニューでパスを指定してください。.
        /// </summary>
        public static string errorGameNotFound {
            get {
                return ResourceManager.GetString("errorGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project IIのコンフィグiniは有効ではありません。.
        /// </summary>
        public static string errorInvalidNP2INI {
            get {
                return ResourceManager.GetString("errorInvalidNP2INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリーが選択されていません.
        /// </summary>
        public static string errorNoCategorySelected {
            get {
                return ResourceManager.GetString("errorNoCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project 2のパスを指定してください.
        /// </summary>
        public static string errorNP2NotFound {
            get {
                return ResourceManager.GetString("errorNP2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像ファイルではありません：
        ///.
        /// </summary>
        public static string errorOpenImage {
            get {
                return ResourceManager.GetString("errorOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームが選択されていません.
        /// </summary>
        public static string errorRandomListEmpty {
            get {
                return ResourceManager.GetString("errorRandomListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replayフォルダが見つかりません.
        /// </summary>
        public static string errorReplaysNotFound {
            get {
                return ResourceManager.GetString("errorReplaysNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vpatch.iniが見つかりません.
        /// </summary>
        public static string errorvpatchNotFound {
            get {
                return ResourceManager.GetString("errorvpatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行ファイル.
        /// </summary>
        public static string executableFilter {
            get {
                return ResourceManager.GetString("executableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームの設定：.
        /// </summary>
        public static string gameConfiguration {
            get {
                return ResourceManager.GetString("gameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームプロファイル.
        /// </summary>
        public static string gameGroup {
            get {
                return ResourceManager.GetString("gameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームID.
        /// </summary>
        public static string gameIDColumn {
            get {
                return ResourceManager.GetString("gameIDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームの実行ファイルを指定する.
        /// </summary>
        public static string gameSelectTitle {
            get {
                return ResourceManager.GetString("gameSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 妖精大戦争.
        /// </summary>
        public static string GFW {
            get {
                return ResourceManager.GetString("GFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 妖精大戦争.
        /// </summary>
        public static string GFWShort {
            get {
                return ResourceManager.GetString("GFWShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 妖精大戦争　～ 東方三月精.
        /// </summary>
        public static string GFWTitle {
            get {
                return ResourceManager.GetString("GFWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方剛欲異聞.
        /// </summary>
        public static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剛欲異聞.
        /// </summary>
        public static string GIShort {
            get {
                return ResourceManager.GetString("GIShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方剛欲異聞　～ 水没した沈愁地獄.
        /// </summary>
        public static string GITitle {
            get {
                return ResourceManager.GetString("GITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バレットフィリア達の闇市場.
        /// </summary>
        public static string HBM {
            get {
                return ResourceManager.GetString("HBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バレットフィリア.
        /// </summary>
        public static string HBMShort {
            get {
                return ResourceManager.GetString("HBMShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バレットフィリア達の闇市場　〜 100th Black Market.
        /// </summary>
        public static string HBMTitle {
            get {
                return ResourceManager.GetString("HBMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDIファイル.
        /// </summary>
        public static string hdiFilter {
            get {
                return ResourceManager.GetString("hdiFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDIファイル:.
        /// </summary>
        public static string hdiLabel {
            get {
                return ResourceManager.GetString("hdiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームのHDIファイルを指定する.
        /// </summary>
        public static string hdiSelectTitle {
            get {
                return ResourceManager.GetString("hdiSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方心綺楼.
        /// </summary>
        public static string HM {
            get {
                return ResourceManager.GetString("HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 心綺楼.
        /// </summary>
        public static string HMShort {
            get {
                return ResourceManager.GetString("HMShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方心綺楼　～ Hopeless Masquerade.
        /// </summary>
        public static string HMTitle {
            get {
                return ResourceManager.GetString("HMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方靈異伝.
        /// </summary>
        public static string HRtP {
            get {
                return ResourceManager.GetString("HRtP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 靈異伝.
        /// </summary>
        public static string HRtPShort {
            get {
                return ResourceManager.GetString("HRtPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方靈異伝　～ Highly Responsive to Prayers.
        /// </summary>
        public static string HRtPTitle {
            get {
                return ResourceManager.GetString("HRtPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方天空璋.
        /// </summary>
        public static string HSiFS {
            get {
                return ResourceManager.GetString("HSiFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天空璋.
        /// </summary>
        public static string HSiFSShort {
            get {
                return ResourceManager.GetString("HSiFSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方天空璋　～ Hidden Star in Four Seasons.
        /// </summary>
        public static string HSiFSTitle {
            get {
                return ResourceManager.GetString("HSiFSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方萃夢想.
        /// </summary>
        public static string IaMP {
            get {
                return ResourceManager.GetString("IaMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 萃夢想.
        /// </summary>
        public static string IaMPShort {
            get {
                return ResourceManager.GetString("IaMPShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方萃夢想　～ Immaterial and Missing Power.
        /// </summary>
        public static string IaMPTitle {
            get {
                return ResourceManager.GetString("IaMPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string idColumn {
            get {
                return ResourceManager.GetString("idColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像ファイル.
        /// </summary>
        public static string imageFilter {
            get {
                return ResourceManager.GetString("imageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方永夜抄.
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方ランチャーについて.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永夜抄.
        /// </summary>
        public static string INShort {
            get {
                return ResourceManager.GetString("INShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方永夜抄　～ Imperishable Night.
        /// </summary>
        public static string INTitle {
            get {
                return ResourceManager.GetString("INTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アマノジャク.
        /// </summary>
        public static string ISC {
            get {
                return ResourceManager.GetString("ISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アマノジャク.
        /// </summary>
        public static string ISCShort {
            get {
                return ResourceManager.GetString("ISCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弾幕アマノジャク　～ Impossible Spell Card.
        /// </summary>
        public static string ISCTitle {
            get {
                return ResourceManager.GetString("ISCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行ファイルの場所：.
        /// </summary>
        public static string jpLabel {
            get {
                return ResourceManager.GetString("jpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語：.
        /// </summary>
        public static string langLabel {
            get {
                return ResourceManager.GetString("langLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大アイコン.
        /// </summary>
        public static string largeIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("largeIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動.
        /// </summary>
        public static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全般.
        /// </summary>
        public static string launcherSettings {
            get {
                return ResourceManager.GetString("launcherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一覧.
        /// </summary>
        public static string listToolStripMenuItem {
            get {
                return ResourceManager.GetString("listToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方幻想郷.
        /// </summary>
        public static string LLS {
            get {
                return ResourceManager.GetString("LLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幻想郷.
        /// </summary>
        public static string LLSShort {
            get {
                return ResourceManager.GetString("LLSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方幻想郷　～ Lotus Land Story.
        /// </summary>
        public static string LLSTitle {
            get {
                return ResourceManager.GetString("LLSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方紺珠伝.
        /// </summary>
        public static string LoLK {
            get {
                return ResourceManager.GetString("LoLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紺珠伝.
        /// </summary>
        public static string LoLKShort {
            get {
                return ResourceManager.GetString("LoLKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方紺珠伝　～ Legacy of Lunatic Kingdom.
        /// </summary>
        public static string LoLKTitle {
            get {
                return ResourceManager.GetString("LoLKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整数作.
        /// </summary>
        public static string mainGroup {
            get {
                return ResourceManager.GetString("mainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トレイに最小化.
        /// </summary>
        public static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方風神録.
        /// </summary>
        public static string MoF {
            get {
                return ResourceManager.GetString("MoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風神録.
        /// </summary>
        public static string MoFShort {
            get {
                return ResourceManager.GetString("MoFShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方風神録　～ Mountain of Faith.
        /// </summary>
        public static string MoFTitle {
            get {
                return ResourceManager.GetString("MoFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方怪綺談.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 怪綺談.
        /// </summary>
        public static string MSShort {
            get {
                return ResourceManager.GetString("MSShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方怪綺談　～ Mystic Square.
        /// </summary>
        public static string MSTitle {
            get {
                return ResourceManager.GetString("MSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string newCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("newCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project IIの場所：.
        /// </summary>
        public static string np2Label {
            get {
                return ResourceManager.GetString("np2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project IIの実行ファイルを指定する.
        /// </summary>
        public static string np2SelectTitle {
            get {
                return ResourceManager.GetString("np2SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appdataフォルダ.
        /// </summary>
        public static string openAppdata {
            get {
                return ResourceManager.GetString("openAppdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダを開く.
        /// </summary>
        public static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダを開く.
        /// </summary>
        public static string openFolderToolStripMenuItem {
            get {
                return ResourceManager.GetString("openFolderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project IIのフォルダを開く.
        /// </summary>
        public static string openNP2Folder {
            get {
                return ResourceManager.GetString("openNP2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replayフォルダ.
        /// </summary>
        public static string openReplays {
            get {
                return ResourceManager.GetString("openReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vpatch.iniを編集.
        /// </summary>
        public static string openvpatch {
            get {
                return ResourceManager.GetString("openvpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applocaleで開く.
        /// </summary>
        public static string openWithApplocaleToolStripMenuItem {
            get {
                return ResourceManager.GetString("openWithApplocaleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パッチ.
        /// </summary>
        public static string patchColumn {
            get {
                return ResourceManager.GetString("patchColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタムプロファイル.
        /// </summary>
        public static string patchGroup {
            get {
                return ResourceManager.GetString("patchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームパス.
        /// </summary>
        public static string pathColumn {
            get {
                return ResourceManager.GetString("pathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧作.
        /// </summary>
        public static string pc98Group {
            get {
                return ResourceManager.GetString("pc98Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-98版用.
        /// </summary>
        public static string pc98Settings {
            get {
                return ResourceManager.GetString("pc98Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方妖々夢.
        /// </summary>
        public static string PCB {
            get {
                return ResourceManager.GetString("PCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 妖々夢.
        /// </summary>
        public static string PCBShort {
            get {
                return ResourceManager.GetString("PCBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方妖々夢　～ Perfect Cherry Blossom.
        /// </summary>
        public static string PCBTitle {
            get {
                return ResourceManager.GetString("PCBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムでゲームを起動.
        /// </summary>
        public static string playRandomToolStripMenuItem {
            get {
                return ResourceManager.GetString("playRandomToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方夢時空.
        /// </summary>
        public static string PoDD {
            get {
                return ResourceManager.GetString("PoDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夢時空.
        /// </summary>
        public static string PoDDShort {
            get {
                return ResourceManager.GetString("PoDDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方夢時空　～ Phantasmagoria of Dim.Dream.
        /// </summary>
        public static string PoDDTitle {
            get {
                return ResourceManager.GetString("PoDDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方花映塚.
        /// </summary>
        public static string PoFV {
            get {
                return ResourceManager.GetString("PoFV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 花映塚.
        /// </summary>
        public static string PoFVShort {
            get {
                return ResourceManager.GetString("PoFVShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方花映塚　～ Phantasmagoria of Flower View.
        /// </summary>
        public static string PoFVTitle {
            get {
                return ResourceManager.GetString("PoFVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダム.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        public static string randomAll {
            get {
                return ResourceManager.GetString("randomAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムで起動したいゲームを選んでください.
        /// </summary>
        public static string randomLabel {
            get {
                return ResourceManager.GetString("randomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        public static string randomNone {
            get {
                return ResourceManager.GetString("randomNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダム起動.
        /// </summary>
        public static string randomSettings {
            get {
                return ResourceManager.GetString("randomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムでゲームを起動します.
        /// </summary>
        public static string RandomTitle {
            get {
                return ResourceManager.GetString("RandomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前の変更.
        /// </summary>
        public static string renameCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前の変更.
        /// </summary>
        public static string renameToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos;に&apos;{0}&apos;をダウンロードします.
        /// </summary>
        public static string replayDownload {
            get {
                return ResourceManager.GetString("replayDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リプレイをダウンロードしますか？.
        /// </summary>
        public static string replayDownloadTitle {
            get {
                return ResourceManager.GetString("replayDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リプレイファイル.
        /// </summary>
        public static string replayFilter {
            get {
                return ResourceManager.GetString("replayFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リプレイリストがいっぱいです。（風神録はユーザーリプレイをサポートしていません）
        ///.
        /// </summary>
        public static string replayFull {
            get {
                return ResourceManager.GetString("replayFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リプレイ.
        /// </summary>
        public static string replays {
            get {
                return ResourceManager.GetString("replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方地霊殿.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地霊殿.
        /// </summary>
        public static string SAShort {
            get {
                return ResourceManager.GetString("SAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方地霊殿　～ Subterranean Animism.
        /// </summary>
        public static string SATitle {
            get {
                return ResourceManager.GetString("SATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたパッチ.
        /// </summary>
        public static string selectedPatches {
            get {
                return ResourceManager.GetString("selectedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トレイアイコンを常に表示する.
        /// </summary>
        public static string showTray {
            get {
                return ResourceManager.GetString("showTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小アイコン.
        /// </summary>
        public static string smallIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("smallIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方封魔録.
        /// </summary>
        public static string SoEW {
            get {
                return ResourceManager.GetString("SoEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封魔録.
        /// </summary>
        public static string SoEWShort {
            get {
                return ResourceManager.GetString("SoEWShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方封魔録　～ the Story of Eastern Wonderland.
        /// </summary>
        public static string SoEWTitle {
            get {
                return ResourceManager.GetString("SoEWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並べ替え.
        /// </summary>
        public static string sortToolStripMenuItem {
            get {
                return ResourceManager.GetString("sortToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小数点作.
        /// </summary>
        public static string spinoffGroup {
            get {
                return ResourceManager.GetString("spinoffGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方文花帖.
        /// </summary>
        public static string StB {
            get {
                return ResourceManager.GetString("StB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文花帖.
        /// </summary>
        public static string StBShort {
            get {
                return ResourceManager.GetString("StBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方文花帖　～ Shoot the Bullet.
        /// </summary>
        public static string StBTitle {
            get {
                return ResourceManager.GetString("StBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方緋想天.
        /// </summary>
        public static string SWR {
            get {
                return ResourceManager.GetString("SWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緋想天.
        /// </summary>
        public static string SWRShort {
            get {
                return ResourceManager.GetString("SWRShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方緋想天 ～ Scarlet Weather Rhapsody.
        /// </summary>
        public static string SWRTitle {
            get {
                return ResourceManager.GetString("SWRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黄昏フロンティア作.
        /// </summary>
        public static string tasofroGroup {
            get {
                return ResourceManager.GetString("tasofroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方神霊廟.
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神霊廟.
        /// </summary>
        public static string TDShort {
            get {
                return ResourceManager.GetString("TDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方神霊廟　～ Ten Desires.
        /// </summary>
        public static string TDTitle {
            get {
                return ResourceManager.GetString("TDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトルの表示.
        /// </summary>
        public static string textToolStripMenuItem {
            get {
                return ResourceManager.GetString("textToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロファイルの設定：.
        /// </summary>
        public static string thcrapTitle {
            get {
                return ResourceManager.GetString("thcrapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並べて表示.
        /// </summary>
        public static string tileToolStripMenuItem {
            get {
                return ResourceManager.GetString("tileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方ランチャー.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル.
        /// </summary>
        public static string titleColumn {
            get {
                return ResourceManager.GetString("titleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string trayExit {
            get {
                return ResourceManager.GetString("trayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        public static string trayOpen {
            get {
                return ResourceManager.GetString("trayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムでゲームを起動.
        /// </summary>
        public static string trayRandom {
            get {
                return ResourceManager.GetString("trayRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方獣王園.
        /// </summary>
        public static string UDoALG {
            get {
                return ResourceManager.GetString("UDoALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獣王園.
        /// </summary>
        public static string UDoALGShort {
            get {
                return ResourceManager.GetString("UDoALGShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方獣王園　〜 Unfinished Dream of All Living Ghost.
        /// </summary>
        public static string UDoALGTitle {
            get {
                return ResourceManager.GetString("UDoALGTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方星蓮船.
        /// </summary>
        public static string UFO {
            get {
                return ResourceManager.GetString("UFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 星蓮船.
        /// </summary>
        public static string UFOShort {
            get {
                return ResourceManager.GetString("UFOShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方星蓮船　～ Undefined Fantastic Object.
        /// </summary>
        public static string UFOTitle {
            get {
                return ResourceManager.GetString("UFOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方深秘録.
        /// </summary>
        public static string ULiL {
            get {
                return ResourceManager.GetString("ULiL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深秘録.
        /// </summary>
        public static string ULiLShort {
            get {
                return ResourceManager.GetString("ULiLShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方深秘録　～ Urban Legend in Limbo.
        /// </summary>
        public static string ULiLTitle {
            get {
                return ResourceManager.GetString("ULiLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方虹龍洞.
        /// </summary>
        public static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虹龍洞.
        /// </summary>
        public static string UMShort {
            get {
                return ResourceManager.GetString("UMShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方虹龍洞 ～ Unconnected Marketeers.
        /// </summary>
        public static string UMTitle {
            get {
                return ResourceManager.GetString("UMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方非想天則.
        /// </summary>
        public static string UoNL {
            get {
                return ResourceManager.GetString("UoNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非想天則.
        /// </summary>
        public static string UoNLShort {
            get {
                return ResourceManager.GetString("UoNLShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方非想天則　～ 超弩級ギニョルの謎を追え.
        /// </summary>
        public static string UoNLTitle {
            get {
                return ResourceManager.GetString("UoNLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppLocaleで実行.
        /// </summary>
        public static string useApplocale {
            get {
                return ResourceManager.GetString("useApplocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秘封ナイトメアダイアリー.
        /// </summary>
        public static string VD {
            get {
                return ResourceManager.GetString("VD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナイトメアダイアリー.
        /// </summary>
        public static string VDShort {
            get {
                return ResourceManager.GetString("VDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秘封ナイトメアダイアリー　〜 Violet Detector.
        /// </summary>
        public static string VDTitle {
            get {
                return ResourceManager.GetString("VDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        public static string viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方鬼形獣.
        /// </summary>
        public static string WBaWC {
            get {
                return ResourceManager.GetString("WBaWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鬼形獣.
        /// </summary>
        public static string WBaWCShort {
            get {
                return ResourceManager.GetString("WBaWCShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方鬼形獣　～ Wily Beast and Weakest Creature.
        /// </summary>
        public static string WBaWCTitle {
            get {
                return ResourceManager.GetString("WBaWCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows版用.
        /// </summary>
        public static string windowsSettings {
            get {
                return ResourceManager.GetString("windowsSettings", resourceCulture);
            }
        }
    }
}
