//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touhou_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touhou_Launcher.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string allFilter {
            get {
                return ResourceManager.GetString("allFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ascendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("ascendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Close.
        /// </summary>
        public static string autoClose {
            get {
                return ResourceManager.GetString("autoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically close the launcher after launching a game.
        /// </summary>
        public static string autoCloseToolTip {
            get {
                return ResourceManager.GetString("autoCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey Banner.
        /// </summary>
        public static string bannerOffLabel {
            get {
                return ResourceManager.GetString("bannerOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the grey banner.
        /// </summary>
        public static string bannerOffSelectTitle {
            get {
                return ResourceManager.GetString("bannerOffSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored Banner.
        /// </summary>
        public static string bannerOnLabel {
            get {
                return ResourceManager.GetString("bannerOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the colored banner.
        /// </summary>
        public static string bannerOnSelectTitle {
            get {
                return ResourceManager.GetString("bannerOnSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Settings.
        /// </summary>
        public static string bannerSettings {
            get {
                return ResourceManager.GetString("bannerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 120 x 44.
        /// </summary>
        public static string bannerSize {
            get {
                return ResourceManager.GetString("bannerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show banner?.
        /// </summary>
        public static string bannerToolStripMenuItem {
            get {
                return ResourceManager.GetString("bannerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Color.
        /// </summary>
        public static string btnCustomText {
            get {
                return ResourceManager.GetString("btnCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Button.
        /// </summary>
        public static string buttonToolStripMenuItem {
            get {
                return ResourceManager.GetString("buttonToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom banner.
        /// </summary>
        public static string chkCustomBanner {
            get {
                return ResourceManager.GetString("chkCustomBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom text color.
        /// </summary>
        public static string chkCustomText {
            get {
                return ResourceManager.GetString("chkCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Game.
        /// </summary>
        public static string configureToolStripMenuItem {
            get {
                return ResourceManager.GetString("configureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure thcrap.
        /// </summary>
        public static string crapConfigure {
            get {
                return ResourceManager.GetString("crapConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap Location:.
        /// </summary>
        public static string crapDirLabel {
            get {
                return ResourceManager.GetString("crapDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap Profile:.
        /// </summary>
        public static string crapLabel {
            get {
                return ResourceManager.GetString("crapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string crapResetStartingRepo {
            get {
                return ResourceManager.GetString("crapResetStartingRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thcrap Starting Repository:.
        /// </summary>
        public static string crapStartingRepoLabel {
            get {
                return ResourceManager.GetString("crapStartingRepoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string customAdd {
            get {
                return ResourceManager.GetString("customAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category &apos;{0}&apos; and all of its contents?.
        /// </summary>
        public static string customCategoryDeleteConfirm {
            get {
                return ResourceManager.GetString("customCategoryDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        public static string customDeleteConfirm {
            get {
                return ResourceManager.GetString("customDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Games.
        /// </summary>
        public static string customGames {
            get {
                return ResourceManager.GetString("customGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.exe:.
        /// </summary>
        public static string customLabel {
            get {
                return ResourceManager.GetString("customLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Game.
        /// </summary>
        public static string customRemove {
            get {
                return ResourceManager.GetString("customRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese/vpatch.ini, English (non-THCRAP), Custom.exe, thcrap.
        /// </summary>
        public static string defaultExec {
            get {
                return ResourceManager.GetString("defaultExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Executable:.
        /// </summary>
        public static string defaultLabel {
            get {
                return ResourceManager.GetString("defaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string deleteCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string descendingToolStripMenuItem {
            get {
                return ResourceManager.GetString("descendingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descriptionColumn {
            get {
                return ResourceManager.GetString("descriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detailsToolStripMenuItem {
            get {
                return ResourceManager.GetString("detailsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Executable:.
        /// </summary>
        public static string enLabel {
            get {
                return ResourceManager.GetString("enLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Appdata Folder.
        /// </summary>
        public static string errorAppdataNotFound {
            get {
                return ResourceManager.GetString("errorAppdataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set thcrap&apos;s profile.
        /// </summary>
        public static string errorcrapConfigNotSet {
            get {
                return ResourceManager.GetString("errorcrapConfigNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set thcrap&apos;s location.
        /// </summary>
        public static string errorcrapNotFound {
            get {
                return ResourceManager.GetString("errorcrapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found.
        /// </summary>
        public static string errorFileNotFound {
            get {
                return ResourceManager.GetString("errorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game. Please check the path in the right click menu..
        /// </summary>
        public static string errorGameNotFound {
            get {
                return ResourceManager.GetString("errorGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project II&apos;s configuration ini is not valid..
        /// </summary>
        public static string errorInvalidNP2INI {
            get {
                return ResourceManager.GetString("errorInvalidNP2INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Category Selected.
        /// </summary>
        public static string errorNoCategorySelected {
            get {
                return ResourceManager.GetString("errorNoCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Neko Project 2&apos;s location.
        /// </summary>
        public static string errorNP2NotFound {
            get {
                return ResourceManager.GetString("errorNP2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file as image:
        ///.
        /// </summary>
        public static string errorOpenImage {
            get {
                return ResourceManager.GetString("errorOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Games Selected.
        /// </summary>
        public static string errorRandomListEmpty {
            get {
                return ResourceManager.GetString("errorRandomListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Replays folder.
        /// </summary>
        public static string errorReplaysNotFound {
            get {
                return ResourceManager.GetString("errorReplaysNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find vpatch.ini.
        /// </summary>
        public static string errorvpatchNotFound {
            get {
                return ResourceManager.GetString("errorvpatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files.
        /// </summary>
        public static string executableFilter {
            get {
                return ResourceManager.GetString("executableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Configuration: .
        /// </summary>
        public static string gameConfiguration {
            get {
                return ResourceManager.GetString("gameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Profiles.
        /// </summary>
        public static string gameGroup {
            get {
                return ResourceManager.GetString("gameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID.
        /// </summary>
        public static string gameIDColumn {
            get {
                return ResourceManager.GetString("gameIDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Executable.
        /// </summary>
        public static string gameSelectTitle {
            get {
                return ResourceManager.GetString("gameSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image Files.
        /// </summary>
        public static string hdiFilter {
            get {
                return ResourceManager.GetString("hdiFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game HDI:.
        /// </summary>
        public static string hdiLabel {
            get {
                return ResourceManager.GetString("hdiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game&apos;s HDI.
        /// </summary>
        public static string hdiSelectTitle {
            get {
                return ResourceManager.GetString("hdiSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string idColumn {
            get {
                return ResourceManager.GetString("idColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string imageFilter {
            get {
                return ResourceManager.GetString("imageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese/vpatch Executable:.
        /// </summary>
        public static string jpLabel {
            get {
                return ResourceManager.GetString("jpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string langLabel {
            get {
                return ResourceManager.GetString("langLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icons.
        /// </summary>
        public static string largeIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("largeIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Settings.
        /// </summary>
        public static string launcherSettings {
            get {
                return ResourceManager.GetString("launcherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string listToolStripMenuItem {
            get {
                return ResourceManager.GetString("listToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Games.
        /// </summary>
        public static string mainGroup {
            get {
                return ResourceManager.GetString("mainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string newCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("newCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neko Project II Location:.
        /// </summary>
        public static string np2Label {
            get {
                return ResourceManager.GetString("np2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neko Project II&apos;s executable.
        /// </summary>
        public static string np2SelectTitle {
            get {
                return ResourceManager.GetString("np2SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appdata Folder.
        /// </summary>
        public static string openAppdata {
            get {
                return ResourceManager.GetString("openAppdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string openFolderToolStripMenuItem {
            get {
                return ResourceManager.GetString("openFolderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Neko Project II Folder.
        /// </summary>
        public static string openNP2Folder {
            get {
                return ResourceManager.GetString("openNP2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Replays Folder.
        /// </summary>
        public static string openReplays {
            get {
                return ResourceManager.GetString("openReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vpatch.ini.
        /// </summary>
        public static string openvpatch {
            get {
                return ResourceManager.GetString("openvpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Applocale.
        /// </summary>
        public static string openWithApplocaleToolStripMenuItem {
            get {
                return ResourceManager.GetString("openWithApplocaleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch.
        /// </summary>
        public static string patchColumn {
            get {
                return ResourceManager.GetString("patchColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Profile.
        /// </summary>
        public static string patchGroup {
            get {
                return ResourceManager.GetString("patchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string pathColumn {
            get {
                return ResourceManager.GetString("pathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-98 Games.
        /// </summary>
        public static string pc98Group {
            get {
                return ResourceManager.GetString("pc98Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-98 Game Settings.
        /// </summary>
        public static string pc98Settings {
            get {
                return ResourceManager.GetString("pc98Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Random.
        /// </summary>
        public static string playRandomToolStripMenuItem {
            get {
                return ResourceManager.GetString("playRandomToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string randomAll {
            get {
                return ResourceManager.GetString("randomAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games that will be included in the
        ///random game option:.
        /// </summary>
        public static string randomLabel {
            get {
                return ResourceManager.GetString("randomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string randomNone {
            get {
                return ResourceManager.GetString("randomNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Game Settings.
        /// </summary>
        public static string randomSettings {
            get {
                return ResourceManager.GetString("randomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a Random Game.
        /// </summary>
        public static string RandomTitle {
            get {
                return ResourceManager.GetString("RandomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Category.
        /// </summary>
        public static string renameCategoryToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameCategoryToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string renameToolStripMenuItem {
            get {
                return ResourceManager.GetString("renameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &apos;{0}&apos; to:
        ///&apos;{1}&apos;.
        /// </summary>
        public static string replayDownload {
            get {
                return ResourceManager.GetString("replayDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Replay?.
        /// </summary>
        public static string replayDownloadTitle {
            get {
                return ResourceManager.GetString("replayDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Files.
        /// </summary>
        public static string replayFilter {
            get {
                return ResourceManager.GetString("replayFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player replays full and Touhou 10 does not support user replays.
        ///.
        /// </summary>
        public static string replayFull {
            get {
                return ResourceManager.GetString("replayFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replays.
        /// </summary>
        public static string replays {
            get {
                return ResourceManager.GetString("replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Patches.
        /// </summary>
        public static string selectedPatches {
            get {
                return ResourceManager.GetString("selectedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show tray icon.
        /// </summary>
        public static string showTray {
            get {
                return ResourceManager.GetString("showTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icons.
        /// </summary>
        public static string smallIconsToolStripMenuItem {
            get {
                return ResourceManager.GetString("smallIconsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string sortToolStripMenuItem {
            get {
                return ResourceManager.GetString("sortToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinoffs.
        /// </summary>
        public static string spinoffGroup {
            get {
                return ResourceManager.GetString("spinoffGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilight Frontier Games.
        /// </summary>
        public static string tasofroGroup {
            get {
                return ResourceManager.GetString("tasofroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Text?.
        /// </summary>
        public static string textToolStripMenuItem {
            get {
                return ResourceManager.GetString("textToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highly Responsive to Prayers.
        /// </summary>
        public static string Th01 {
            get {
                return ResourceManager.GetString("Th01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRtP.
        /// </summary>
        public static string Th01Short {
            get {
                return ResourceManager.GetString("Th01Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 01: Highly Responsive to Prayers.
        /// </summary>
        public static string Th01Title {
            get {
                return ResourceManager.GetString("Th01Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story of Eastern Wonderland.
        /// </summary>
        public static string Th02 {
            get {
                return ResourceManager.GetString("Th02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoEW.
        /// </summary>
        public static string Th02Short {
            get {
                return ResourceManager.GetString("Th02Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 02: the Story of Eastern Wonderland.
        /// </summary>
        public static string Th02Title {
            get {
                return ResourceManager.GetString("Th02Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasmagoria of Dim. Dream.
        /// </summary>
        public static string Th03 {
            get {
                return ResourceManager.GetString("Th03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoDD.
        /// </summary>
        public static string Th03Short {
            get {
                return ResourceManager.GetString("Th03Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 03: Phantasmagoria of Dim. Dream.
        /// </summary>
        public static string Th03Title {
            get {
                return ResourceManager.GetString("Th03Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus Land Story.
        /// </summary>
        public static string Th04 {
            get {
                return ResourceManager.GetString("Th04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLS.
        /// </summary>
        public static string Th04Short {
            get {
                return ResourceManager.GetString("Th04Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 04: Lotus Land Story.
        /// </summary>
        public static string Th04Title {
            get {
                return ResourceManager.GetString("Th04Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystic Square.
        /// </summary>
        public static string Th05 {
            get {
                return ResourceManager.GetString("Th05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string Th05Short {
            get {
                return ResourceManager.GetString("Th05Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 05: Mystic Square.
        /// </summary>
        public static string Th05Title {
            get {
                return ResourceManager.GetString("Th05Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embodiment of Scarlet Devil.
        /// </summary>
        public static string Th06 {
            get {
                return ResourceManager.GetString("Th06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EoSD.
        /// </summary>
        public static string Th06Short {
            get {
                return ResourceManager.GetString("Th06Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 06: the Embodiment of Scarlet Devil.
        /// </summary>
        public static string Th06Title {
            get {
                return ResourceManager.GetString("Th06Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Cherry Blossom.
        /// </summary>
        public static string Th07 {
            get {
                return ResourceManager.GetString("Th07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immaterial and Missing Power.
        /// </summary>
        public static string Th075 {
            get {
                return ResourceManager.GetString("Th075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IaMP.
        /// </summary>
        public static string Th075Short {
            get {
                return ResourceManager.GetString("Th075Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 07.5: Immaterial and Missing Power.
        /// </summary>
        public static string Th075Title {
            get {
                return ResourceManager.GetString("Th075Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB.
        /// </summary>
        public static string Th07Short {
            get {
                return ResourceManager.GetString("Th07Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 07: Perfect Cherry Blossom.
        /// </summary>
        public static string Th07Title {
            get {
                return ResourceManager.GetString("Th07Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperishable Night.
        /// </summary>
        public static string Th08 {
            get {
                return ResourceManager.GetString("Th08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string Th08Short {
            get {
                return ResourceManager.GetString("Th08Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 08: Imperishable Night.
        /// </summary>
        public static string Th08Title {
            get {
                return ResourceManager.GetString("Th08Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasmagoria of Flower View.
        /// </summary>
        public static string Th09 {
            get {
                return ResourceManager.GetString("Th09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot the Bullet.
        /// </summary>
        public static string Th095 {
            get {
                return ResourceManager.GetString("Th095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StB.
        /// </summary>
        public static string Th095Short {
            get {
                return ResourceManager.GetString("Th095Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 09.5: Shoot the Bullet.
        /// </summary>
        public static string Th095Title {
            get {
                return ResourceManager.GetString("Th095Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoFV.
        /// </summary>
        public static string Th09Short {
            get {
                return ResourceManager.GetString("Th09Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 09: Phantasmagoria of Flower View.
        /// </summary>
        public static string Th09Title {
            get {
                return ResourceManager.GetString("Th09Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain of Faith.
        /// </summary>
        public static string Th10 {
            get {
                return ResourceManager.GetString("Th10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarlet Weather Rhapsody.
        /// </summary>
        public static string Th105 {
            get {
                return ResourceManager.GetString("Th105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWR.
        /// </summary>
        public static string Th105Short {
            get {
                return ResourceManager.GetString("Th105Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 10.5: Scarlet Weather Rhapsody.
        /// </summary>
        public static string Th105Title {
            get {
                return ResourceManager.GetString("Th105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoF.
        /// </summary>
        public static string Th10Short {
            get {
                return ResourceManager.GetString("Th10Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 10: Mountain of Faith.
        /// </summary>
        public static string Th10Title {
            get {
                return ResourceManager.GetString("Th10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subterranean Animism.
        /// </summary>
        public static string Th11 {
            get {
                return ResourceManager.GetString("Th11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string Th11Short {
            get {
                return ResourceManager.GetString("Th11Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 11: Subterranean Animism.
        /// </summary>
        public static string Th11Title {
            get {
                return ResourceManager.GetString("Th11Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Fantastic Object.
        /// </summary>
        public static string Th12 {
            get {
                return ResourceManager.GetString("Th12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisoutensoku.
        /// </summary>
        public static string Th123 {
            get {
                return ResourceManager.GetString("Th123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisoutensoku.
        /// </summary>
        public static string Th123Short {
            get {
                return ResourceManager.GetString("Th123Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.3: Hisoutensoku.
        /// </summary>
        public static string Th123Title {
            get {
                return ResourceManager.GetString("Th123Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Spoiler.
        /// </summary>
        public static string Th125 {
            get {
                return ResourceManager.GetString("Th125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        public static string Th125Short {
            get {
                return ResourceManager.GetString("Th125Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.5: Double Spoiler.
        /// </summary>
        public static string Th125Title {
            get {
                return ResourceManager.GetString("Th125Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Fairy Wars.
        /// </summary>
        public static string Th128 {
            get {
                return ResourceManager.GetString("Th128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFW.
        /// </summary>
        public static string Th128Short {
            get {
                return ResourceManager.GetString("Th128Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12.8: Great Fairy Wars.
        /// </summary>
        public static string Th128Title {
            get {
                return ResourceManager.GetString("Th128Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFO.
        /// </summary>
        public static string Th12Short {
            get {
                return ResourceManager.GetString("Th12Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 12: Undefined Fantastic Object.
        /// </summary>
        public static string Th12Title {
            get {
                return ResourceManager.GetString("Th12Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten Desires.
        /// </summary>
        public static string Th13 {
            get {
                return ResourceManager.GetString("Th13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopeless Masquerade.
        /// </summary>
        public static string Th135 {
            get {
                return ResourceManager.GetString("Th135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM.
        /// </summary>
        public static string Th135Short {
            get {
                return ResourceManager.GetString("Th135Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 13.5: Hopeless Masquerade.
        /// </summary>
        public static string Th135Title {
            get {
                return ResourceManager.GetString("Th135Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        public static string Th13Short {
            get {
                return ResourceManager.GetString("Th13Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 13: Ten Desires.
        /// </summary>
        public static string Th13Title {
            get {
                return ResourceManager.GetString("Th13Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Dealing Character.
        /// </summary>
        public static string Th14 {
            get {
                return ResourceManager.GetString("Th14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible Spell Card.
        /// </summary>
        public static string Th143 {
            get {
                return ResourceManager.GetString("Th143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISC.
        /// </summary>
        public static string Th143Short {
            get {
                return ResourceManager.GetString("Th143Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14.3: Impossible Spell Card.
        /// </summary>
        public static string Th143Title {
            get {
                return ResourceManager.GetString("Th143Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban Legend in Limbo.
        /// </summary>
        public static string Th145 {
            get {
                return ResourceManager.GetString("Th145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULiL.
        /// </summary>
        public static string Th145Short {
            get {
                return ResourceManager.GetString("Th145Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14.5: Urban Legend in Limbo.
        /// </summary>
        public static string Th145Title {
            get {
                return ResourceManager.GetString("Th145Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDC.
        /// </summary>
        public static string Th14Short {
            get {
                return ResourceManager.GetString("Th14Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 14: Double Dealing Character.
        /// </summary>
        public static string Th14Title {
            get {
                return ResourceManager.GetString("Th14Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy of Lunatic Kingdom.
        /// </summary>
        public static string Th15 {
            get {
                return ResourceManager.GetString("Th15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antinomy of Common Flowers.
        /// </summary>
        public static string Th155 {
            get {
                return ResourceManager.GetString("Th155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoCF.
        /// </summary>
        public static string Th155Short {
            get {
                return ResourceManager.GetString("Th155Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 15.5: Antinomy of Common Flowers.
        /// </summary>
        public static string Th155Title {
            get {
                return ResourceManager.GetString("Th155Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoLK.
        /// </summary>
        public static string Th15Short {
            get {
                return ResourceManager.GetString("Th15Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 15: Legacy of Lunatic Kingdom.
        /// </summary>
        public static string Th15Title {
            get {
                return ResourceManager.GetString("Th15Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Star in Four Seasons.
        /// </summary>
        public static string Th16 {
            get {
                return ResourceManager.GetString("Th16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet Detector.
        /// </summary>
        public static string Th165 {
            get {
                return ResourceManager.GetString("Th165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VD.
        /// </summary>
        public static string Th165Short {
            get {
                return ResourceManager.GetString("Th165Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 16.5: Violet Detector.
        /// </summary>
        public static string Th165Title {
            get {
                return ResourceManager.GetString("Th165Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSiFS.
        /// </summary>
        public static string Th16Short {
            get {
                return ResourceManager.GetString("Th16Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 16: Hidden Star in Four Seasons.
        /// </summary>
        public static string Th16Title {
            get {
                return ResourceManager.GetString("Th16Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wily Beast and Weakest Creature.
        /// </summary>
        public static string Th17 {
            get {
                return ResourceManager.GetString("Th17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gouyoku Ibun.
        /// </summary>
        public static string Th175 {
            get {
                return ResourceManager.GetString("Th175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        public static string Th175Short {
            get {
                return ResourceManager.GetString("Th175Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 17.5: Gouyoku Ibun.
        /// </summary>
        public static string Th175Title {
            get {
                return ResourceManager.GetString("Th175Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBaWC.
        /// </summary>
        public static string Th17Short {
            get {
                return ResourceManager.GetString("Th17Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 17: Wily Beast and Weakest Creature.
        /// </summary>
        public static string Th17Title {
            get {
                return ResourceManager.GetString("Th17Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconnected Marketeers.
        /// </summary>
        public static string Th18 {
            get {
                return ResourceManager.GetString("Th18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100th Black Market.
        /// </summary>
        public static string Th185 {
            get {
                return ResourceManager.GetString("Th185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100BM.
        /// </summary>
        public static string Th185Short {
            get {
                return ResourceManager.GetString("Th185Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 18.5: 100th Black Market.
        /// </summary>
        public static string Th185Title {
            get {
                return ResourceManager.GetString("Th185Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        public static string Th18Short {
            get {
                return ResourceManager.GetString("Th18Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 18: Unconnected Marketeers.
        /// </summary>
        public static string Th18Title {
            get {
                return ResourceManager.GetString("Th18Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished Dream of All Living Ghost.
        /// </summary>
        public static string Th19 {
            get {
                return ResourceManager.GetString("Th19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDoALG.
        /// </summary>
        public static string Th19Short {
            get {
                return ResourceManager.GetString("Th19Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou 19: Unfinished Dream of All Living Ghost.
        /// </summary>
        public static string Th19Title {
            get {
                return ResourceManager.GetString("Th19Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Configuration: .
        /// </summary>
        public static string thcrapTitle {
            get {
                return ResourceManager.GetString("thcrapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string tileToolStripMenuItem {
            get {
                return ResourceManager.GetString("tileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou Launcher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string titleColumn {
            get {
                return ResourceManager.GetString("titleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string trayExit {
            get {
                return ResourceManager.GetString("trayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string trayOpen {
            get {
                return ResourceManager.GetString("trayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Game.
        /// </summary>
        public static string trayRandom {
            get {
                return ResourceManager.GetString("trayRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Applocale.
        /// </summary>
        public static string useApplocale {
            get {
                return ResourceManager.GetString("useApplocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Game Settings.
        /// </summary>
        public static string windowsSettings {
            get {
                return ResourceManager.GetString("windowsSettings", resourceCulture);
            }
        }
    }
}
